branches:
  only:
    - main
language: node_js
node_js:
  - 16

services:
  - docker

script:
## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

## Tagging
  - docker tag udagram-api-feed huydn6/udagram-api-feed:latest
  - docker tag udagram-api-user huydn6/udagram-api-user:latest
  - docker tag udagram-frontend huydn6/udagram-frontend:latest
  - docker tag reverseproxy huydn6/reverseproxy:latest
after_success:
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push huydn6/udagram-api-feed:latest
  - docker push huydn6/udagram-api-user:latest
  - docker push huydn6/udagram-frontend:latest
  - docker push huydn6/reverseproxy:latest